// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "fce31a52-67af-4a8d-b592-5e7fc4d097a2",
                            Name = "Yönetici"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "6ce33da1-9a60-4ad8-b656-803893851200",
                            Name = "Personel"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnnualLeave")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("IIF((DATEDIFF(year, [EmploymentDate], GETDATE())) > 15, 26, IIF((DATEDIFF(year, [EmploymentDate], GETDATE())) > 5, 20, 14))");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("GrossSalary")
                        .HasColumnType("float");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TCNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("remainingDayOff")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1978, 9, 28, 22, 6, 25, 868, DateTimeKind.Local).AddTicks(7157),
                            ConcurrencyStamp = "292eb366-e70e-414d-beb3-65aedb776c15",
                            DepartmentID = 1,
                            Email = "jane.doe@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 872, DateTimeKind.Local).AddTicks(8175),
                            FirstName = "Jane",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "face10.jpg",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "JANE.DOE@SIRKETADI.COM",
                            NormalizedUserName = "JANE.DOE",
                            PasswordHash = "AQAAAAEAACcQAAAAEC1hOVDCTECysOT/3bQJSr2CUJpsfusJMqa66HGAifWuB4LMMsvw/ImcUNHuphjrRQ==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Doe",
                            SecurityStamp = "65C5E7CD7F053342A01A595BFCD6E8BC",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Yönetici",
                            TwoFactorEnabled = false,
                            UserName = "jane.doe",
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1996, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3729),
                            ConcurrencyStamp = "0e217fb6-3352-4dfe-9005-75a7b80c648e",
                            DepartmentID = 2,
                            Email = "ogun.erkutay@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3752),
                            FirstName = "Ogün",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "Erkutay",
                            LockoutEnabled = false,
                            NormalizedEmail = "OGUN.ERKUTAY@SIRKETADI.COM",
                            NormalizedUserName = "OGUN.ERKUTAY",
                            PasswordHash = "AQAAAAEAACcQAAAAEBg+GoCve/4RkXw9Y8RJAQ/hoMTkFXQDd3yDl8rrbV/gZzmWP80QmhzbKlqCyXM+uw==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Erkutay",
                            SecurityStamp = "7ED842E82E049244B3ECCDC3030EABC8",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Memur",
                            TwoFactorEnabled = false,
                            UserName = "ogun.erkutay",
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1995, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3763),
                            ConcurrencyStamp = "3e18302a-80b7-481d-a1c1-936590886c8a",
                            DepartmentID = 3,
                            Email = "esraezgi.erdogan@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3765),
                            FirstName = "Esra",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-2.jpg",
                            LastName = "Erdoğan",
                            LockoutEnabled = false,
                            NormalizedEmail = "ESRAEZGI.ERDOGAN@SIRKETADI.COM",
                            NormalizedUserName = "ESRAEZGI.ERDOGAN",
                            PasswordHash = "AQAAAAEAACcQAAAAEAKGQ3DYGBgOL6QDbt0m+Iturg9CqIqwyn7C8Z17/dcSkswX2osQXHmsm2iHQS25PQ==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Ezgi",
                            SecurityStamp = "BF8993B3A53E5749B4A4F5184CF2F1C9",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Aşçı",
                            TwoFactorEnabled = false,
                            UserName = "esraezgi.erdogan",
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1994, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3771),
                            ConcurrencyStamp = "77b49453-f688-4028-aa25-2ca297a9c62b",
                            DepartmentID = 4,
                            Email = "sinem.pamik@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3773),
                            FirstName = "Sinem",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-2.jpg",
                            LastName = "Pamık",
                            LockoutEnabled = false,
                            NormalizedEmail = "SINEM.PAMIK@SIRKETADI.COM",
                            NormalizedUserName = "SINEM.PAMIK",
                            PasswordHash = "AQAAAAEAACcQAAAAEDxYS+dudQnARoCaCOe8azROOsyfYJUIYDoy5KM9bG1TCHGwXDNYVHuPVspTIW7uPw==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "",
                            SecurityStamp = "C36443C1AB5C8D438563464AE23FB6B5",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Çayçı",
                            TwoFactorEnabled = false,
                            UserName = "sinem.pamik",
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1993, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3785),
                            ConcurrencyStamp = "b1142127-1511-409a-bf5f-d9d84e8c02a3",
                            DepartmentID = 5,
                            Email = "cerennur.genlikkara@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3787),
                            FirstName = "Ceren",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-2.jpg",
                            LastName = "Genlik Kara",
                            LockoutEnabled = false,
                            NormalizedEmail = "CERENNUR.GENLIKKARA@SIRKETADI.COM",
                            NormalizedUserName = "CERENNUR.GENLIK",
                            PasswordHash = "AQAAAAEAACcQAAAAENb4IMb6Dx7vyNiE+NcIgS9fU/Hc3EbIzx3005t/ZAaYB7mpGOevYI0O0qpSoTCQfQ==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Nur",
                            SecurityStamp = "526F881DF1023D4FA1D83FB427E755A8",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Reklamcı",
                            TwoFactorEnabled = false,
                            UserName = "cerennur.genlikkara",
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1992, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3792),
                            ConcurrencyStamp = "b0362da7-dbd5-40a2-b18a-ec2e57b5570d",
                            DepartmentID = 6,
                            Email = "berkayfettah.hacioglu@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3794),
                            FirstName = "Berkay",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "Hacıoğlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "BERKAYFETTAH.HACIOGLU@SIRKETADI.COM",
                            NormalizedUserName = "BERKAYFETTAH.HACIOGLU",
                            PasswordHash = "AQAAAAEAACcQAAAAED+BhI3v8QwcGPruEq4sOfrcbukQvXAAZe2WhBNfS1ocqucgswPY2VisnxdcaTfJAg==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Fettah",
                            SecurityStamp = "3728E22116F5864B8C857C6A81C1893F",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Pazarlamacı",
                            TwoFactorEnabled = false,
                            UserName = "berkayfettah.hacioglu",
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1991, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3800),
                            ConcurrencyStamp = "75304013-b343-4137-aeb3-4b6dd5445c93",
                            DepartmentID = 7,
                            Email = "mahmutmustafa.zekeriyaoglu@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3801),
                            FirstName = "Mahmut",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "Zekeriyaoğlu",
                            LockoutEnabled = false,
                            NormalizedEmail = "MAHMUTMUSTAFA.ZEKERIYAOGLU@SIRKETADI.COM",
                            NormalizedUserName = "MAHMUTMUSTAFA.ZEKERIYEOGLU",
                            PasswordHash = "AQAAAAEAACcQAAAAECk3s4g7RfcBa4tJOqJbHsPRl0U1iY/FJBoDsMGMrBSQMIindjr5bZR+Dq9yw0ob8Q==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Mustafa",
                            SecurityStamp = "1E1C4EB0861F3A4FA521A3117F93D7C1",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Satışcı",
                            TwoFactorEnabled = false,
                            UserName = "mahmutmustafa.zekeriyaoglu",
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1990, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3809),
                            ConcurrencyStamp = "90b6255b-5e4e-4532-956e-f6bde6b8c78c",
                            DepartmentID = 8,
                            Email = "ismaelabraham.mcdoe@sirketadi.com",
                            EmailConfirmed = true,
                            EmploymentDate = new DateTime(2017, 9, 28, 22, 6, 25, 873, DateTimeKind.Local).AddTicks(3810),
                            FirstName = "Ismael",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "McDoe",
                            LockoutEnabled = false,
                            NormalizedEmail = "ISMAELABRAHAM.MCDOE@SIRKETADI.COM",
                            NormalizedUserName = "ISMAELABRAHAM.MCDOE",
                            PasswordHash = "AQAAAAEAACcQAAAAEH50QJ51oS+VW7g5Aef95B4CcJ91qm+0tyrag6NQPggIWHnI4QVjDxlRzVt4WdVpZg==",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Abraham",
                            SecurityStamp = "031121BF604BBF4EB17C3CEA8B0D866B",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Gezici",
                            TwoFactorEnabled = false,
                            UserName = "ismaelabraham.mcdoe",
                            remainingDayOff = 0
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUserAndWorkShift", b =>
                {
                    b.Property<int>("WorkShiftID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.HasKey("WorkShiftID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUserAndWorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.DayOff", b =>
                {
                    b.Property<int>("DayOffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<bool>("DepartmentApproval")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date");

                    b.Property<bool>("ManagerApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.HasKey("DayOffID");

                    b.HasIndex("AppUserID");

                    b.ToTable("DayOffs");
                });

            modelBuilder.Entity("EntityLayer.Entities.Debit", b =>
                {
                    b.Property<int>("DebitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GivenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DebitID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Debits");
                });

            modelBuilder.Entity("EntityLayer.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "Yönetim"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "Üretim"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentName = "İnsan Kaynakları"
                        },
                        new
                        {
                            DepartmentID = 5,
                            DepartmentName = "Muhasebe"
                        },
                        new
                        {
                            DepartmentID = 6,
                            DepartmentName = "Pazarlama"
                        },
                        new
                        {
                            DepartmentID = 7,
                            DepartmentName = "Satın Alma"
                        },
                        new
                        {
                            DepartmentID = 8,
                            DepartmentName = "Lojistik"
                        },
                        new
                        {
                            DepartmentID = 9,
                            DepartmentName = "Güvenlik"
                        },
                        new
                        {
                            DepartmentID = 10,
                            DepartmentName = "Mühendislik"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.DepartmentAndWorkShift", b =>
                {
                    b.Property<int>("WorkShiftID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentAndWorkShiftID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("Date");

                    b.HasKey("WorkShiftID", "DepartmentID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("DepartmentAndWorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.EmploymentDetails", b =>
                {
                    b.Property<int>("EmploymentDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DismissalDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmploymentDetailsID");

                    b.HasIndex("AppUserID");

                    b.ToTable("EmploymentDetails");
                });

            modelBuilder.Entity("EntityLayer.Entities.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DemandDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("ExpenseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManagerApproval")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("ExpenseID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("EntityLayer.Entities.Overtime", b =>
                {
                    b.Property<int>("OvertimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DemandDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ManHour")
                        .HasColumnType("float");

                    b.Property<bool>("ManagerApproval")
                        .HasColumnType("bit");

                    b.Property<string>("OvertimeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("OvertimeID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Overtimes");
                });

            modelBuilder.Entity("EntityLayer.Entities.WorkHour", b =>
                {
                    b.Property<int>("WorkHourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkHourID");

                    b.HasIndex("AppUserID");

                    b.ToTable("WorkHours");
                });

            modelBuilder.Entity("EntityLayer.Entities.WorkShift", b =>
                {
                    b.Property<int>("WorkShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BreakTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BreakTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkShiftID");

                    b.ToTable("WorkShifts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUser", b =>
                {
                    b.HasOne("EntityLayer.Entities.Department", "Department")
                        .WithMany("AppUsers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUserAndWorkShift", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.WorkShift", "WorkShift")
                        .WithMany()
                        .HasForeignKey("WorkShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.DayOff", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("DayOffs")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.Debit", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("Debits")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.DepartmentAndWorkShift", b =>
                {
                    b.HasOne("EntityLayer.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.WorkShift", "WorkShift")
                        .WithMany()
                        .HasForeignKey("WorkShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.EmploymentDetails", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("EmploymentDetails")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.Expense", b =>
                {
                    b.HasOne("EntityLayer.Entities.Department", "Department")
                        .WithMany("Expenses")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EntityLayer.Entities.Overtime", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("Overtimes")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.WorkHour", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("WorkHours")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUser", b =>
                {
                    b.Navigation("DayOffs");

                    b.Navigation("Debits");

                    b.Navigation("EmploymentDetails");

                    b.Navigation("Overtimes");

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("EntityLayer.Entities.Department", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
