// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "56f40559-3da9-40ce-b8b7-ed5aad1fb0d6",
                            Name = "Yönetici"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "69d426e6-32ea-44d6-86a7-08e717688e31",
                            Name = "Personel"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AnnualLeave")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("IIF((DATEDIFF(year, [EmploymentDate], GETDATE())) > 15, 26, IIF((DATEDIFF(year, [EmploymentDate], GETDATE())) > 5, 20, 14))");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<double>("GrossSalary")
                        .HasColumnType("float");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("TCNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("remainingDayOff")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1978, 9, 27, 16, 47, 21, 300, DateTimeKind.Local).AddTicks(4053),
                            ConcurrencyStamp = "95158615-7de4-4edb-90b0-68dc54def998",
                            DepartmentID = 1,
                            Email = "jane.doe@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(2101),
                            FirstName = "Jane",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "face10.jpg",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Doe",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Yönetici",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1996, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3586),
                            ConcurrencyStamp = "f9b0ca6d-895a-416a-96d9-a2515e802b53",
                            DepartmentID = 2,
                            Email = "ogun.erkutay@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3592),
                            FirstName = "Ogün",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "Erkutay",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Erkutay",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Memur",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1995, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3597),
                            ConcurrencyStamp = "d6561aa0-cedb-4934-9289-a2e424d54f20",
                            DepartmentID = 3,
                            Email = "esraezgi.erdogan@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3599),
                            FirstName = "Esra",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-2.jpg",
                            LastName = "Erdoğan",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Ezgi",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Aşçı",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1994, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3603),
                            ConcurrencyStamp = "e1292951-693c-4c9f-a875-c7b2c7947cf2",
                            DepartmentID = 4,
                            Email = "sinem.pamik@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3605),
                            FirstName = "Sinem",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-2.jpg",
                            LastName = "Pamık",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Çayçı",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1993, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3609),
                            ConcurrencyStamp = "457787e8-1e10-4495-ba67-03d999c25438",
                            DepartmentID = 5,
                            Email = "cerennur.genlikkara@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3610),
                            FirstName = "Ceren",
                            Gender = 1,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-2.jpg",
                            LastName = "Genlik Kara",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Nur",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Reklamcı",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1992, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3622),
                            ConcurrencyStamp = "c0ec3ec6-74b2-4520-882e-2f665ba842cf",
                            DepartmentID = 6,
                            Email = "berkayfettah.hacioglu@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3624),
                            FirstName = "Berkay",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "Hacıoğlu",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Fettah",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Pazarlamacı",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1991, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3628),
                            ConcurrencyStamp = "41034e7b-9cb1-47df-a456-0f6e92c30881",
                            DepartmentID = 7,
                            Email = "mahmutmustafa.zekeriyaoglu@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3629),
                            FirstName = "Mahmut",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "Zekeriyaoğlu",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Mustafa",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Satışcı",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1990, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3633),
                            ConcurrencyStamp = "75816e14-eeec-442f-9cb4-478bec6a0828",
                            DepartmentID = 8,
                            Email = "ismaelabraham.mcdoe@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3634),
                            FirstName = "Ismael",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "McDoe",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Abraham",
                            Status = true,
                            TCNO = "12345678912",
                            Title = "Gezici",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            Address = "Atatürk, Fatih Sultan Mehmet Cd. No:63, 34764 Ümraniye/İstanbul",
                            AnnualLeave = 0,
                            BirthDate = new DateTime(1989, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3638),
                            ConcurrencyStamp = "6ae60bde-89b5-473c-a255-4d336babb47c",
                            DepartmentID = 9,
                            Email = "azazelchristian.mcdonald@sirketadi.com",
                            EmailConfirmed = false,
                            EmploymentDate = new DateTime(2017, 9, 27, 16, 47, 21, 301, DateTimeKind.Local).AddTicks(3640),
                            FirstName = "Azazel",
                            Gender = 2,
                            GrossSalary = 10000.0,
                            ImagePath = "pic-1.jpg",
                            LastName = "MCDonald",
                            LockoutEnabled = false,
                            PasswordHash = "c873586a09e16d54ef49b9ae978cd98db8edc49aaebdb4dcf460d83514321c38",
                            PhoneNumber = "5325212112",
                            PhoneNumberConfirmed = true,
                            SecondName = "Christian",
                            Status = false,
                            TCNO = "12345678912",
                            Title = "Yiyici",
                            TwoFactorEnabled = false,
                            remainingDayOff = 0
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUserAndWorkShift", b =>
                {
                    b.Property<int>("WorkShiftID")
                        .HasColumnType("int");

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.HasKey("WorkShiftID", "AppUserID");

                    b.HasIndex("AppUserID");

                    b.ToTable("AppUserAndWorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.DayOff", b =>
                {
                    b.Property<int>("DayOffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<bool>("DepartmentApproval")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("Date");

                    b.Property<bool>("ManagerApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("Date");

                    b.HasKey("DayOffID");

                    b.HasIndex("AppUserID");

                    b.ToTable("DayOffs");
                });

            modelBuilder.Entity("EntityLayer.Entities.Debit", b =>
                {
                    b.Property<int>("DebitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GivenDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DebitID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Debits");
                });

            modelBuilder.Entity("EntityLayer.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentID = 1,
                            DepartmentName = "Yönetim"
                        },
                        new
                        {
                            DepartmentID = 2,
                            DepartmentName = "Üretim"
                        },
                        new
                        {
                            DepartmentID = 3,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentID = 4,
                            DepartmentName = "İnsan Kaynakları"
                        },
                        new
                        {
                            DepartmentID = 5,
                            DepartmentName = "Muhasebe"
                        },
                        new
                        {
                            DepartmentID = 6,
                            DepartmentName = "Pazarlama"
                        },
                        new
                        {
                            DepartmentID = 7,
                            DepartmentName = "Satın Alma"
                        },
                        new
                        {
                            DepartmentID = 8,
                            DepartmentName = "Lojistik"
                        },
                        new
                        {
                            DepartmentID = 9,
                            DepartmentName = "Güvenlik"
                        },
                        new
                        {
                            DepartmentID = 10,
                            DepartmentName = "Mühendislik"
                        });
                });

            modelBuilder.Entity("EntityLayer.Entities.DepartmentAndWorkShift", b =>
                {
                    b.Property<int>("WorkShiftID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentAndWorkShiftID")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("Date");

                    b.HasKey("WorkShiftID", "DepartmentID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("DepartmentAndWorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.EmploymentDetails", b =>
                {
                    b.Property<int>("EmploymentDetailsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DismissalDate")
                        .HasColumnType("Date");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmploymentDetailsID");

                    b.HasIndex("AppUserID");

                    b.ToTable("EmploymentDetails");
                });

            modelBuilder.Entity("EntityLayer.Entities.Expense", b =>
                {
                    b.Property<int>("ExpenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DemandDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("ExpenseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ManagerApproval")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("ExpenseID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("EntityLayer.Entities.Overtime", b =>
                {
                    b.Property<int>("OvertimeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DemandDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("ManHour")
                        .HasColumnType("float");

                    b.Property<bool>("ManagerApproval")
                        .HasColumnType("bit");

                    b.Property<string>("OvertimeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Urgency")
                        .HasColumnType("int");

                    b.HasKey("OvertimeID");

                    b.HasIndex("AppUserID");

                    b.ToTable("Overtimes");
                });

            modelBuilder.Entity("EntityLayer.Entities.WorkHour", b =>
                {
                    b.Property<int>("WorkHourID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkHourID");

                    b.HasIndex("AppUserID");

                    b.ToTable("WorkHours");
                });

            modelBuilder.Entity("EntityLayer.Entities.WorkShift", b =>
                {
                    b.Property<int>("WorkShiftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BreakTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BreakTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("WorkShiftID");

                    b.ToTable("WorkShifts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUser", b =>
                {
                    b.HasOne("EntityLayer.Entities.Department", "Department")
                        .WithMany("AppUsers")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUserAndWorkShift", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.WorkShift", "WorkShift")
                        .WithMany()
                        .HasForeignKey("WorkShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.DayOff", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("DayOffs")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.Debit", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("Debits")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.DepartmentAndWorkShift", b =>
                {
                    b.HasOne("EntityLayer.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.WorkShift", "WorkShift")
                        .WithMany()
                        .HasForeignKey("WorkShiftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("WorkShift");
                });

            modelBuilder.Entity("EntityLayer.Entities.EmploymentDetails", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("EmploymentDetails")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.Expense", b =>
                {
                    b.HasOne("EntityLayer.Entities.Department", "Department")
                        .WithMany("Expenses")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EntityLayer.Entities.Overtime", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("Overtimes")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("EntityLayer.Entities.WorkHour", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", "AppUser")
                        .WithMany("WorkHours")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("EntityLayer.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EntityLayer.Entities.AppUser", b =>
                {
                    b.Navigation("DayOffs");

                    b.Navigation("Debits");

                    b.Navigation("EmploymentDetails");

                    b.Navigation("Overtimes");

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("EntityLayer.Entities.Department", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
